# Generated by Django 3.1.7 on 2021-02-28 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurent_photo', models.ImageField(upload_to='blog/%Y/%m/%d')),
                ('restaurent_name', models.CharField(default='', max_length=120, verbose_name='Restaurant name')),
                ('restaurent_address', models.TextField(default='', max_length=120, verbose_name='Restaurant address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurent',
                'verbose_name_plural': 'Restaurents',
            },
        ),
        migrations.CreateModel(
            name='Restaurent_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_photo', models.ImageField(upload_to='blog/%Y/%m/%d')),
                ('product_price', models.CharField(default='', max_length=120, verbose_name='Product price')),
                ('product_categories', models.CharField(choices=[('SWEET', 'Sweet'), ('SAVORY', 'Savory'), ('JUICE', 'Juice')], default='', max_length=120, verbose_name='Product Categories')),
                ('description', models.TextField(default='', max_length=120, verbose_name='Description')),
                ('promotional_price', models.IntegerField(verbose_name='Promotional Price')),
                ('on_sale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurent product',
                'verbose_name_plural': 'Restaurent products',
            },
        ),
        migrations.CreateModel(
            name='Restaurent_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_and_closing_days', models.CharField(default='', max_length=120, verbose_name='Opening and closing days')),
                ('opening_and_closing_hours', models.CharField(default='', max_length=120, verbose_name='Opening and closing hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spark_eighteen_app.restaurent')),
            ],
            options={
                'verbose_name': 'Restaurent schedule',
                'verbose_name_plural': 'Restaurent schedules',
            },
        ),
        migrations.CreateModel(
            name='Product_sale_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.CharField(default='', max_length=120, verbose_name='Product price')),
                ('time_of_the_day', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurent_product', models.ManyToManyField(to='spark_eighteen_app.Restaurent_product')),
            ],
            options={
                'verbose_name': 'Product sale information',
                'verbose_name_plural': 'Product sale informations',
            },
        ),
    ]
