# Generated by Django 3.1.7 on 2021-02-28 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spark_eighteen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurent_schedule',
            name='restaurents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurent', to='spark_eighteen_app.restaurent'),
        ),
    ]
