# Generated by Django 3.1.7 on 2021-02-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spark_eighteen_app', '0004_auto_20210228_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent_product',
            name='restaurent_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurent_product', to='spark_eighteen_app.restaurent'),
        ),
    ]
