# Generated by Django 3.1.7 on 2021-02-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_eighteen_app', '0005_restaurent_product_restaurent_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurent_product',
            name='product_price',
            field=models.FloatField(default='', verbose_name='Product price'),
        ),
    ]
