# Generated by Django 3.1.7 on 2021-02-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_eighteen_app', '0006_auto_20210228_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent_product',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Product Name'),
        ),
    ]
