# Generated by Django 3.1.7 on 2021-02-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_eighteen_app', '0007_restaurent_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_sale_info',
            name='restaurent_product',
            field=models.ManyToManyField(blank=True, related_name='product_sale_info', to='spark_eighteen_app.Restaurent_product'),
        ),
    ]
