# Generated by Django 3.1.7 on 2021-03-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark_eighteen_app', '0008_auto_20210228_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_sale_info',
            name='time_of_the_day',
            field=models.DateTimeField(),
        ),
    ]
